insert into talent (id,name,rating,brand,role,tier,salary,is_champion,title) values
('cody-rhodes','Cody Rhodes',95,'SmackDown','Wrestler','Main Event',18000000,true,'Undisputed WWE Champion'),
('roman-reigns','Roman Reigns',97,'Raw','Wrestler','Franchise Star',30000000,true,'World Heavyweight Champion'),
('liv-morgan','Liv Morgan',89,'Raw','Wrestler','Upper Midcard',10000000,true,'Women''s World Champion'),
('rhea-ripley','Rhea Ripley',96,'Raw','Wrestler','Franchise Star',30000000,true,'WWE Women''s Champion'),
('penta','Penta',86,'Raw','Wrestler','Featured',10000000,true,'Intercontinental Champion'),
('trick-williams','Trick Williams',86,'SmackDown','Wrestler','Breakout Star',10000000,true,'United States Champion'),
('becky-lynch','Becky Lynch',94,'Raw','Wrestler','Main Event',22000000,true,'Women''s Intercontinental Champion'),
('tiffany-stratton','Tiffany Stratton',85,'SmackDown','Wrestler','Featured',6500000,true,'Women''s United States Champion'),
('damian-priest','Damian Priest',88,'SmackDown','Wrestler','Upper Midcard',10000000,true,'WWE Tag Team Champion'),
('r-truth','R-Truth',82,'SmackDown','Wrestler','Character TV',6500000,true,'WWE Tag Team Champion'),
('seth-rollins','Seth Rollins',93,'Raw','Wrestler','Main Event',22000000,false,null),
('cm-punk','CM Punk',93,'Raw','Wrestler','Main Event',22000000,false,null),
('gunther','Gunther',92,'Raw','Wrestler','Main Event',16000000,false,null),
('randy-orton','Randy Orton',91,'SmackDown','Wrestler','Main Event',16000000,false,null),
('jey-uso','Jey Uso',90,'Raw','Wrestler','Top Star',16000000,false,null),
('logan-paul','Logan Paul',90,'SmackDown','Wrestler','Special Attraction',16000000,false,null),
('drew-mcintyre','Drew McIntyre',91,'Raw','Wrestler','Main Event',16000000,false,null),
('bianca-belair','Bianca Belair',95,'SmackDown','Wrestler','Main Event',22000000,false,null),
('charlotte-flair','Charlotte Flair',94,'SmackDown','Wrestler','Main Event',22000000,false,null),
('aj-styles','AJ Styles',89,'SmackDown','Wrestler','Upper Midcard',10000000,false,null),
('la-knight','LA Knight',88,'SmackDown','Wrestler','Upper Midcard',10000000,false,null),
('bayley','Bayley',88,'SmackDown','Wrestler','Upper Midcard',10000000,false,null),
('sami-zayn','Sami Zayn',87,'Raw','Wrestler','Upper Midcard',10000000,false,null),
('kevin-owens','Kevin Owens',87,'SmackDown','Wrestler','Upper Midcard',10000000,false,null),
('finn-balor','Finn Balor',87,'Raw','Wrestler','Upper Midcard',10000000,false,null),
('iyo-sky','IYO SKY',88,'Raw','Wrestler','Upper Midcard',10000000,false,null),
('asuka','Asuka',89,'Raw','Wrestler','Upper Midcard',10000000,false,null),
('jade-cargill','Jade Cargill',87,'SmackDown','Wrestler','Featured',10000000,false,null),
('naomi','Naomi',84,'SmackDown','Wrestler','Featured',6500000,false,null),
('nia-jax','Nia Jax',86,'SmackDown','Wrestler','Featured',10000000,false,null),
('dominik-mysterio','Dominik Mysterio',83,'Raw','Wrestler','Featured TV',6500000,false,null),
('chad-gable','Chad Gable',80,'Raw','Wrestler','Workhorse',3500000,false,null),
('dragon-lee','Dragon Lee',81,'Raw','Wrestler','Workhorse',3500000,false,null),
('carmelo-hayes','Carmelo Hayes',82,'SmackDown','Wrestler','Featured TV',6500000,false,null),
('andrade','Andrade',84,'SmackDown','Wrestler','Featured',6500000,false,null),
('bron-breakker','Bron Breakker',86,'Raw','Wrestler','Featured',10000000,false,null),
('solo-sikoa','Solo Sikoa',86,'SmackDown','Wrestler','Featured',10000000,false,null),
('jacob-fatu','Jacob Fatu',87,'SmackDown','Wrestler','Featured',10000000,false,null),
('paul-heyman','Paul Heyman',96,'SmackDown','Manager','Elite Manager',7500000,false,null),
('adam-pearce','Adam Pearce',82,'Raw','Authority Figure','GM',3000000,false,null),
('nick-aldis','Nick Aldis',84,'SmackDown','Authority Figure','GM',3000000,false,null),
('michael-cole','Michael Cole',94,'Raw','Commentator','Lead Announcer',8000000,false,null),
('corey-graves','Corey Graves',88,'Raw','Commentator','Color Commentator',5000000,false,null),
('joe-tessitore','Joe Tessitore',86,'SmackDown','Commentator','Play-by-Play',5000000,false,null),
('wade-barrett','Wade Barrett',86,'SmackDown','Commentator','Color Commentator',5000000,false,null),
('cathy-kelley','Cathy Kelley',82,'Raw','Interviewer','Backstage Interviewer',1500000,false,null),
('byron-saxton','Byron Saxton',80,'SmackDown','Interviewer','Backstage Interviewer',900000,false,null),
('stone-cold','Stone Cold Steve Austin',98,'Legend','Legend','Mega Legend',35000000,false,null),
('the-rock','The Rock',98,'Legend','Legend','Mega Legend',35000000,false,null),
('undertaker','The Undertaker',97,'Legend','Legend','Mega Legend',35000000,false,null),
('john-cena','John Cena',96,'Legend','Legend','Mega Legend',24000000,false,null),
('trish-stratus','Trish Stratus',94,'Legend','Legend','Legend',24000000,false,null),
('lita','Lita',92,'Legend','Legend','Legend',16000000,false,null)
on conflict (id) do update set
name=excluded.name,
rating=excluded.rating,
brand=excluded.brand,
role=excluded.role,
tier=excluded.tier,
salary=excluded.salary,
is_champion=excluded.is_champion,
title=excluded.title,
updated_at=now();

insert into result_sources (name,url,source_type,priority) values
('WWE.com','https://www.wwe.com/','official','primary'),
('WWE Superstars','https://www.wwe.com/superstars','roster_champions','primary'),
('CBS Sports WWE','https://www.cbssports.com/wwe/','news_recaps','secondary'),
('The SmackDown Hotel WWE Roster','https://www.thesmackdownhotel.com/roster/wwe/','roster_reference','secondary'),
('WWE 2K Ratings','https://www.thesmackdownhotel.com/news/wwe2k26/wwe-2k26-overall-ratings-list-all-superstars-ranked-by-best-rating','ratings','secondary'),
('Wrestling Inc','https://www.wrestlinginc.com/','news_recaps','secondary'),
('Ringside News','https://www.ringsidenews.com/wwe-news/','rumors_context','tertiary'),
('Yahoo Finance TKO','https://finance.yahoo.com/quote/TKO/','stock','primary')
on conflict do nothing;

-- supplemental roster update
insert into talent (id,name,rating,brand,role,tier,salary,is_champion,title) values
('tama-tonga','Tama Tonga',82,'SmackDown','Wrestler','Tag/Featured',6500000,false,null),
('tonga-loa','Tonga Loa',80,'SmackDown','Wrestler','Tag Team',3500000,false,null),
('montez-ford','Montez Ford',82,'SmackDown','Wrestler','Tag/Featured',6500000,false,null),
('angelo-dawkins','Angelo Dawkins',80,'SmackDown','Wrestler','Tag Team',3500000,false,null),
('austin-theory','Austin Theory',82,'SmackDown','Wrestler','Featured TV',6500000,false,null),
('grayson-waller','Grayson Waller',81,'SmackDown','Wrestler','Featured TV',3500000,false,null),
('kofi-kingston','Kofi Kingston',84,'Raw','Wrestler','Tag/Featured',6500000,false,null),
('xavier-woods','Xavier Woods',82,'Raw','Wrestler','Tag/Featured',6500000,false,null),
('raquel-rodriguez','Raquel Rodriguez',83,'Raw','Wrestler','Featured',6500000,false,null),
('lyra-valkyria','Lyra Valkyria',82,'Raw','Wrestler','Featured TV',6500000,false,null),
('chelsea-green','Chelsea Green',80,'SmackDown','Wrestler','Character TV',3500000,false,null),
('piper-niven','Piper Niven',80,'SmackDown','Wrestler','Midcard',3500000,false,null),
('zelina-vega','Zelina Vega',78,'SmackDown','Wrestler','Midcard',3500000,false,null),
('michin','Michin',77,'SmackDown','Wrestler','Midcard',1500000,false,null),
('oba-femi','Oba Femi',85,'NXT','Wrestler','NXT Star',6500000,false,null),
('roxanne-perez','Roxanne Perez',83,'NXT','Wrestler','NXT Star',6500000,false,null),
('sol-ruca','Sol Ruca',80,'NXT','Wrestler','NXT Featured',3500000,false,null),
('lash-legend','Lash Legend',79,'NXT','Wrestler','NXT Featured',3500000,false,null),
('jacy-jayne','Jacy Jayne',79,'NXT','Wrestler','NXT Featured',3500000,false,null),
('tony-dangelo','Tony D''Angelo',80,'NXT','Wrestler','NXT Featured',3500000,false,null),
('vic-joseph','Vic Joseph',82,'NXT','Commentator','Play-by-Play',3000000,false,null),
('booker-t','Booker T',84,'NXT','Commentator','Color Commentator',3000000,false,null),
('pat-mcafee','Pat McAfee',90,'WWE','Commentator','Special Attraction',8000000,false,null),
('alicia-taylor','Alicia Taylor',80,'Raw','Ring Announcer','Ring Announcer',900000,false,null),
('mike-rome','Mike Rome',78,'NXT','Ring Announcer','Ring Announcer',900000,false,null),
('jackie-redmond','Jackie Redmond',82,'Raw','Interviewer','Backstage Interviewer',1500000,false,null),
('hulk-hogan','Hulk Hogan',95,'Legend','Legend','Mega Legend',24000000,false,null),
('shawn-michaels','Shawn Michaels',95,'Legend','Legend','Legend',24000000,false,null),
('kurt-angle','Kurt Angle',94,'Legend','Legend','Legend',24000000,false,null),
('batista','Batista',93,'Legend','Legend','Legend',16000000,false,null)
on conflict (id) do update set
name=excluded.name,
rating=excluded.rating,
brand=excluded.brand,
role=excluded.role,
tier=excluded.tier,
salary=excluded.salary,
is_champion=excluded.is_champion,
title=excluded.title,
updated_at=now();

insert into result_sources (name,url,source_type,priority) values
('Bing WWE Stats Search','https://www.bing.com/search?q=WWE%20Stats%20updates%20reviews','stats_search','tertiary')
on conflict do nothing;
