"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getPlayer, supabase } from "../../../../lib/supabaseClient";
import { leagueMenu, money, salaryFromRating } from "../../../../lib/game";
function Menu({ id }) { return <div className="menu"><strong>☰ Menu</strong><div className="menu-row"><Link href="/leagues">Leagues</Link>{leagueMenu(id).map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}</div></div>; }
export default function Waivers({ params }) {
 const [talent,setTalent]=useState([]); const [owned,setOwned]=useState({}); const [member,setMember]=useState(null); const [msg,setMsg]=useState("");
 useEffect(()=>{load()},[]);
 async function load(){ const user=getPlayer(); const mem=await supabase.from("league_members").select("*").eq("league_id",params.leagueId).eq("user_id",user.id).single(); setMember(mem.data); const t=await supabase.from("talent").select("*").order("rating",{ascending:false}); const r=await supabase.from("rosters").select("talent_id").eq("league_id",params.leagueId); const map={};(r.data||[]).forEach(x=>map[x.talent_id]=true); setOwned(map); setTalent((t.data||[]).filter(x=>!map[x.id])); }
 async function claim(row){ if((member?.waivers_remaining||0)<=0)return setMsg("No waiver claims left this week."); const cost=Math.floor((row.salary||salaryFromRating(row))*0.85); if(member.cash<cost)return setMsg("Not enough cash."); const user=getPlayer(); await supabase.from("rosters").insert({league_id:params.leagueId,player_key:user.id,talent_id:row.id,assigned_brand:row.brand==="SmackDown"?"SmackDown":"Raw",salary:cost}); await supabase.from("league_members").update({cash:member.cash-cost,waivers_remaining:member.waivers_remaining-1}).eq("id",member.id); await supabase.from("ledger").insert({league_id:params.leagueId,player_key:user.id,type:"spent",amount:cost,note:`Waiver claim: ${row.name}`}); setMsg(`Claimed ${row.name}.`); await load(); }
 return <main className="page"><Menu id={params.leagueId}/><h1>Waivers / Free Agency</h1><section className="card"><strong>Claims Remaining</strong><div className="money">{member?.waivers_remaining??0}</div><p className="small">Use this to react to WWE changes without ruining the locked draft system.</p></section><section className="list">{talent.slice(0,40).map(t=><div className="row" key={t.id}><strong>{t.name}</strong><div className="small">{t.role} · {t.brand} · Waiver cost: {money(Math.floor((t.salary||salaryFromRating(t))*0.85))}</div><button onClick={()=>claim(t)}>Claim</button></div>)}</section>{msg&&<p>{msg}</p>}</main>
}